name: rest_api_bloc_pattern
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # dio
  dio: ^5.8.0+1

  # bloc
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # pretty dio logger
  pretty_dio_logger: ^1.4.0

  # go router
  go_router: ^16.0.0

  # equatable:
  equatable: ^2.0.7

  # get it
  get_it: ^8.2.0

  # logger
  logger:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
